In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_digits
df=load_digits()

In [3]:
df.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [5]:
df.target

array([0, 1, 2, ..., 8, 9, 8])

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.data,df.target,test_size=0.3)

In [13]:
#Apply algorithem 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [14]:
lr=LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\Kiran Maske\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1273: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\Kiran Maske\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1288: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(


0.9555555555555556

In [15]:
#SVC
# gamma is a parameter for non linear perspective 

svm = SVC(gamma='auto')
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.42962962962962964

In [17]:
# Random forest 
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9666666666666667

In [18]:
#k-Fold Cross validation on the logistic regression
from sklearn.model_selection import cross_val_score

In [26]:
score_lr = cross_val_score(
    LogisticRegression(solver='liblinear', multi_class='ovr'),
    df.data,
    df.target,
    cv=5);
print(score_lr)
print("Avg:",np.average(score_lr))

C:\Users\Kiran Maske\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1273: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\Kiran Maske\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1288: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
C:\Users\Kiran Maske\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1273: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) inst

[0.92222222 0.88333333 0.95264624 0.95821727 0.89415042]
Avg: 0.9221138966264315


In [29]:
score_svm = cross_val_score (SVC(gamma='auto'),df.data,df.target,cv=3)

   
print(score_svm)
print("Avg:",np.average(score_svm))

[0.38063439 0.41068447 0.51252087]
Avg: 0.4346132442960489


In [35]:
score_rf = cross_val_score( RandomForestClassifier(n_estimators=40),df.data,df.target,cv=5);
print(score_rf)
print("Avg:",np.average(score_rf))

[0.93888889 0.89444444 0.94986072 0.95543175 0.92479109]
Avg: 0.9326833797585887
