In [4]:
import numpy as np 


In [5]:
a1=np.array([1,2,3,4,5])
print(a1)
print(type(a1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
a1.ndim

1

In [7]:
a2=np.array([[1,2,3,4,],[5,6,7,8]])

In [8]:
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
a2.ndim

2

In [11]:
a= np.arange(24)
print(type(a))
# check result that array eith element not separate us 
print(a)
b=list(range(24))

print(b)
print(type(b))

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
<class 'list'>


In [12]:
import numpy as np
l1=[12,13,23,45,56,66]
print(type(l1))
a1=np.array(l1)  # given list convert into array 
print(a1)
type(a1)

<class 'list'>
[12 13 23 45 56 66]


numpy.ndarray

In [13]:
# size.... to chack number of elelment in array 

In [14]:
a2.size  #to check element size

8

In [15]:
# number of rows and coloumn in the array 

In [16]:
print(a2.shape)

(2, 4)


In [17]:
# dtype >>> to check the datatype

In [18]:
a2.dtype

dtype('int32')

In [19]:
a3=np.ones(4)
# onces function by defult create float data
print(a3)
print(a3.dtype)

[1. 1. 1. 1.]
float64


In [21]:
a4=np.ones((3,4),dtype=int)
print(a4)
print(a4.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32


In [22]:
a4.size

12

In [23]:
import numpy as np 
a5=np.zeros(shape=(3,4),dtype=int)
print(a5)
print(a4.dtype)
print(type(a5))
print(a5.ndim)
print(a5.size)
print(a5.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32
<class 'numpy.ndarray'>
2
12
(3, 4)
