In [3]:
import numpy as np
ar1=np.arange(1,18)
print(ar1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [4]:
ar2=np.arange(1,18,2)
#  number 2 indicates it print 
print(ar2)

[ 1  3  5  7  9 11 13 15 17]


In [5]:
# we want change datatype of array 
ar3=np.arange(1,18,2,dtype=float)
print(ar3)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17.]


In [7]:
x=np.linspace(10,20)
#  num is not include & num default is 50 so the range 
# 10 to 20 evaly spaced sample with 50 different object
print(x)

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]


In [9]:
x=np.linspace(10,20,num=5)
#  num value taken 5 so the range is evaluy 10 to 20 is 5
print(x)

[10.  12.5 15.  17.5 20. ]


In [11]:
#end point set to false 
x=np.linspace(10,20,5,endpoint =False)

print(x)

[10. 12. 14. 16. 18.]


In [12]:
x=np.arange(1,13)
print(x)
print("after reshape function")

m= np.reshape(x,(3,4))
print(m)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
after reshape function
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
