In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
pd.read_csv('titanic.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [3]:
df=sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [4]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [5]:
df.describe()

,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [6]:
df2=df[['survived',"pclass",'age','parch']]
df2.head()

,survived,pclass,age,parch
0,0,3,22.0,0
1,1,1,38.0,0
2,1,3,26.0,0
3,1,1,35.0,0
4,0,3,35.0,0


In [7]:
df2.isna().sum()

survived      0
pclass        0
age         177
parch         0
dtype: int64

In [8]:
# now first clean the data 
df3=df2.fillna(df2.mean())

In [9]:
df3.isnull().sum()

survived    0
pclass      0
age         0
parch       0
dtype: int64

In [10]:
#  convert data in matrix and vector form 
#  Bez independent variable in matrix from 
# dependent variable in vector from 

In [12]:
x= df3.drop("survived",axis=1)
#To show the matrix we defined X(capital)
# we drop "survived " because it is depend variable & in matrix we defined 
y=df3["survived"]
# y is use to show vector (for dependent variable)
print('Shape of X',x.shape)
print('Shape of Y',y.shape)

Shape of X (891, 3)
Shape of Y (891,)


In [13]:
#from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=51)
print('Shape of X_train',x_train.shape)
print('Shape of Y_train',y_train.shape)
print('Shape of X_test',x_test.shape)
print('Shape of Y_test',y_test.shape)

Shape of X_train (712, 3)
Shape of Y_train (712,)
Shape of X_test (179, 3)
Shape of Y_test (179,)


In [15]:
sc=StandardScaler()
sc.fit(x_train)

,copy,True
,with_mean,True
,with_std,True


In [16]:
#Attribute 
sc.mean_

array([ 2.30617978, 29.55409121,  0.39185393])

In [17]:
sc.scale_

array([ 0.84405789, 12.99162985,  0.79647463])

In [19]:
x_train.describe()  #diff feature numrical distribution likke mean media 

,pclass,age,parch
count,712.000000,712.000000,712.000000
mean,2.306180,29.554091,0.391854
std,0.844651,13.000763,0.797035
min,1.000000,0.420000,0.000000
25%,1.750000,22.000000,0.000000
50%,3.000000,29.699118,0.000000
75%,3.000000,35.000000,0.000000
max,3.000000,71.000000,5.000000


In [20]:
x_train_sc = sc.transform(x_train)
x_test_sc = sc.transform(x_test)

In [21]:
x_train_sc

array([[ 0.8220055 , -0.42751304, -0.49198545],
       [ 0.8220055 ,  1.997125  , -0.49198545],
       [ 0.8220055 , -1.42815732, -0.49198545],
       ...,
       [ 0.8220055 ,  1.41983023,  3.27461284],
       [ 0.8220055 ,  0.01116307,  0.76354731],
       [ 0.8220055 , -0.08113618, -0.49198545]])

In [22]:
x_train_sc = pd.DataFrame(x_train_sc,columns = ["pclass",'age','parch'])
x_test_sc = pd.DataFrame(x_test_sc,columns = ["pclass",'age','parch'])

In [23]:
x_train

,pclass,age,parch
770,3,24.000000,0
152,3,55.500000,0
731,3,11.000000,0
775,3,18.000000,0
324,3,29.699118,2
...,...,...,...
528,3,39.000000,0
709,3,29.699118,1
736,3,48.000000,3
485,3,29.699118,1


In [24]:
x_train_sc.describe()

,pclass,age,parch
count,7.120000e+02,7.120000e+02,7.120000e+02
mean,1.160121e-16,1.521879e-16,6.237208e-17
std,1.000703e+00,1.000703e+00,1.000703e+00
min,-1.547500e+00,-2.242528e+00,-4.919855e-01
25%,-6.589356e-01,-5.814583e-01,-4.919855e-01
50%,8.220055e-01,1.116307e-02,-4.919855e-01
75%,8.220055e-01,4.191860e-01,-4.919855e-01
max,8.220055e-01,3.190201e+00,5.785678e+00


In [32]:
x_train_mmc = pd.DataFrame(x_train_sc,columns = ["pclass",'age','parch'])
x_test_mmc = pd.DataFrame(x_test_sc,columns = ["pclass",'age','parch'])


In [34]:
x_train_mmc

,pclass,age,parch
0,0.822005,-0.427513,-0.491985
1,0.822005,1.997125,-0.491985
2,0.822005,-1.428157,-0.491985
3,0.822005,-0.889349,-0.491985
4,0.822005,0.011163,2.019080
...,...,...,...
707,0.822005,0.727077,-0.491985
708,0.822005,0.011163,0.763547
709,0.822005,1.419830,3.274613
710,0.822005,0.011163,0.763547


In [35]:
x_train_mmc.describe().round(2)

,pclass,age,parch
count,712.00,712.00,712.00
mean,0.00,0.00,0.00
std,1.00,1.00,1.00
min,-1.55,-2.24,-0.49
25%,-0.66,-0.58,-0.49
50%,0.82,0.01,-0.49
75%,0.82,0.42,-0.49
max,0.82,3.19,5.79


In [37]:
# Min Max Scalear ()
mmc = MinMaxScaler()
mmc.fit(x_train)

,feature_range,"(0, ...)"
,copy,True
,clip,False


In [38]:
x_train_mmc = mmc.transform(x_train)
x_test_mmc = mmc.transform(x_test)

In [39]:
x_train_mmc

array([[1.        , 0.33408898, 0.        ],
       [1.        , 0.78039105, 0.        ],
       [1.        , 0.14990082, 0.        ],
       ...,
       [1.        , 0.67412865, 0.6       ],
       [1.        , 0.4148359 , 0.2       ],
       [1.        , 0.39784642, 0.        ]])

In [40]:
x_test_mmc

array([[0.        , 0.56078209, 0.        ],
       [1.        , 0.44743553, 0.        ],
       [1.        , 0.41909889, 0.        ],
       [0.        , 0.4148359 , 0.        ],
       [0.5       , 0.47577217, 0.2       ],
       [1.        , 0.44743553, 0.        ],
       [0.        , 0.65996033, 0.        ],
       [1.        , 0.22074242, 0.        ],
       [0.5       , 0.9291584 , 0.        ],
       [0.        , 0.2065741 , 0.2       ],
       [0.5       , 0.43326721, 0.        ],
       [0.5       , 0.39076226, 0.        ],
       [0.        , 0.63162369, 0.        ],
       [1.        , 0.31992066, 0.        ],
       [1.        , 0.57495041, 1.        ],
       [0.5       , 0.3482573 , 0.        ],
       [0.5       , 0.50410881, 0.4       ],
       [1.        , 0.4148359 , 0.        ],
       [1.        , 0.4148359 , 0.        ],
       [0.5       , 0.26324738, 0.        ],
       [1.        , 0.4148359 , 0.        ],
       [0.5       , 0.24907906, 0.        ],
       [1.

In [41]:
x_train_mmc = pd.DataFrame(x_train_mmc,columns = ["pclass",'age','parch'])
x_test_mmc = pd.DataFrame(x_test_mmc,columns = ["pclass",'age','parch'])


In [42]:
x_train_mmc.describe().round(2)

,pclass,age,parch
count,712.00,712.00,712.00
mean,0.65,0.41,0.08
std,0.42,0.18,0.16
min,0.00,0.00,0.00
25%,0.38,0.31,0.00
50%,1.00,0.41,0.00
75%,1.00,0.49,0.00
max,1.00,1.00,1.00
